apiVersion: apps/v1
kind: Deployment
metadata:
  name: newwebpage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newwebpage
  template:
    metadata:
      labels:
        app: newwebpage
    spec:
      containers:
      - name: newwebpage-container
        image: madhu1607/newwebpage:latest  
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: newwebpage-service
spec:
  selector:
    app: newwebpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed
